# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(choices=[(1, b'Your colleges organize party for you'), (2, b'Your colleges make present and you make party'), (3, b'Receive money on my birthday and organize party by my self'), (4, b'Organize a party by my self without the present from my colleagues')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_field', models.TextField(max_length=30, verbose_name=b'notes field')),
            ],
        ),
    ]
