# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_fields', models.IntegerField(choices=[(1, b'I would like if my colleges organize party for me'), (2, b'I would like if my colleges make present and I make party'), (3, b'I would like if my colleges give me money on my birthday and I will organize party by my self'), (4, b'I would like organize a party by my self without the present from my colleagues')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_field', models.TextField(max_length=3000, verbose_name=b'notes field')),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='notes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Notes'),
        ),
        migrations.AddField(
            model_name='choices',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
