# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice_field',
            new_name='choice_fields',
        ),
    ]
