# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='notes',
        ),
    ]
