# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170420_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_fields',
            field=models.IntegerField(choices=[(1, b'I would like if my colleges organize party for me'), (2, b'I would like if my colleges make present and I make party'), (3, b'I would like if my colleges give me money on my birthday and I will organize party by my self'), (4, b'I would like organize a party by my self without the present from my colleagues')], default=1),
        ),
    ]
