# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170502_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_field',
            field=models.CharField(max_length=3000, verbose_name=b'notes field'),
        ),
    ]
