# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_auto_20170503_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_fields',
            field=models.IntegerField(choices=[(1, b'I would like if my colleagues organize party for me instead of gift.'), (2, b'I would like if my colleagues give me gift and I will make a party.'), (3, b'I would like if my colleagues give me money on my birthday and I will organize party by my self.'), (4, b'I would like organize a party by my self without the gift from my colleagues.')], default=1),
        ),
    ]
