# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170602_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.TextField(max_length=3000, verbose_name=b'birth date'),
        ),
    ]
