# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170614_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
