# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_choicescreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicescreate',
            old_name='notes_field',
            new_name='choice_field',
        ),
    ]
