# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20170817_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicescreate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
